# Model Parameters
model:
  board_size: 15              # Board dimensions (15x15)
  in_channels: 3              # Number of input channels (black, white, empty)
  num_classes: 225            # 15x15 move positions
  initial_channels: 64        # Channels after initial convolution
  residual_blocks: 3          # Number of residual blocks
  dilations: [1, 2, 4]         # Dilation rates for residual blocks
  multi_scale_dilations: [1, 2, 4]  # Dilations for multi-scale feature extraction
  attention:
    channel_reduction: 16     # Reduction factor for channel attention
    spatial_kernel_size: 7    # Kernel size for spatial attention

# Training Settings
training:
  epochs: 20                  # Number of training epochs
  batch_size: 128             # Batch size for training
  learning_rate: 0.001        # Initial learning rate
  smoothing: 0.1              # Label smoothing factor
  optimizer: "AdamW"          # Optimizer to use
  lr_scheduler: "OneCycleLR"  # Learning rate scheduler
  mixed_precision: true       # Use mixed precision training
  stratified_sampling: true   # Use stratified sampling in data loader
  checkpoint_path: "best_gomoku_model.pth"  # Path to save the best model

# Paths and Data Settings
paths:
  dataset: "gomoku_dataset.npz"  # Processed dataset file
  model_save: "best_gomoku_model.pth"  # Model checkpoint path
  logs: "logs/"                  # Directory for training logs
  psq_dir: "psq_games"           # Directory containing .psq game files

# Data Pipeline Settings
data_pipeline:
  output_size: 15             # Board size for processed examples
  opening_threshold: 10       # Move index threshold for opening phase
  midgame_threshold: 20       # Move index threshold for midgame phase

# Inference Settings
inference:
  temperature: 1.0            # Temperature scaling factor for inference
  visualize: false            # Whether to visualize predictions by default

# GUI Settings
gui:
  cell_size: 30               # Pixel size for each cell on the board
  board_size: 15              # Board dimensions (15x15)
  win_length: 5               # Number of stones in a row to win
